<!-- Created with backwards engineering // Stefan Bröyn -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mo</string>
	</array>
	<key>name</key>
	<string>Modelica</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(parameter|constant|import|connect|initial|inner|outer)\b</string>
			<key>name</key>
	   		<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Real|Integer|Boolean)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict> 
			<key>match</key>
			<string>^\s*([A-Z])(?:([^ ;$]+)(;)?)([.]([A-Z])(?:([^ ;$]+)(;)?)?)++</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b()\b</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(min|max|abs|tan|atan|cos|acos|sin|asin|der)\b</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|if|when|then|loop|end|else|elsewhen|and|break|each|elseif|function)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
	    <dict>
			<key>match</key>
			<string>\b(package|block|model|extends|partial|within)\b</string>
			<key>name</key>
			<string>support.type</string>
		</dict>
	    <dict>
			<key>match</key>
			<string>\b(algorithm|equation|protected|public)\b</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
	    <dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>annotation</string>
			<key>end</key>
			<string>;\s*\n</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.modelica</string>
	<key>uuid</key>
	<string>43df6fac-7928-42e2-9890-f5073aaddb14</string>
</dict>
</plist>
